spring:
  datasource:
    url: jdbc:h2:./db_dev2;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
  data:
    redis:
      host: localhost
      port: 6379